### ISSUE TITLE
Missing manpages 

### ISSUE THREAD

**Issue by dakeryas** [zegervdv/homebrew-zathura#102]
The man pages are missing for zathura:

```
~$ man zathura
No manual entry for zathura
~$ echo $MANPATH
/opt/local/share/man:/opt/homebrew/share/man::
~$ zathura -v
zathura 0.5.2
girara 0.3.9 (runtime: 0.3.9)
(plugin) pdf-poppler (0.3.0) (/opt/homebrew/Cellar/zathura/HEAD-81e541e/lib/zathura/libpdf-poppler.dylib)
```

zathura correctly depends on `sphinx-doc` which should trigger the installation of the man pages. But this block  `zathura.rb` seems to be the culprit.

```
    inreplace "meson.build" do |s|
      s.gsub! "subdir('doc')", ""
    end
```

Removing this block and installing manually with `brew reinstall --build-from-source ./zathura.rb` does fix it (I had also installed the `sphinx` package on top of just `sphinx-doc`).

**Comment by zegervdv** [comment]
There were some issues in the past with building the manpages which let to the exclusion.
But if everything works, feel free to send a PR.

**Comment by dakeryas** [comment]
Fixed by [PR103](https://github.com/zegervdv/homebrew-zathura/pull/103)
