### ISSUE TITLE
Can't add a theme or change background color

### ISSUE THREAD

**Issue by aravezskinteeth** [zegervdv/homebrew-zathura#106]
## Description of the problem

I installed the `--HEAD` version of `zathura`, `girara` and `mudpdf` on MacOS 12.6.2.

Then, I created `~/.config/zathura/zathurarc`, and added the following.

```
set selection-clipboard clipboard
map <C-i> zoom in
map <C-o> zoom out
include catppuccin-macchiato
```

Previously, I followed [these steps](https://github.com/catppuccin/zathura) so I could add a theme.

However, instead of getting this (the gray background), which is what I expected:

![image](https://user-images.githubusercontent.com/104392087/224559800-f009592e-ef83-4102-a3d3-aec0f95f4a23.png)

I didn't see any changes:

<img width="842" alt="SCR-20230312-fgi" src="https://user-images.githubusercontent.com/104392087/224559827-809b452f-eef0-4002-ad3d-8c27b5df2434.png">

I also tried to copy the contents of the [theme file](https://github.com/catppuccin/zathura/blob/main/src/catppuccin-macchiato) at the bottom of my `zathurarc` file, and quit and reopened the terminal but nothing happened.

> I should mention that the other configuration commands, such as `set selection-clipboad clipboard` and the mapping of keys did work.

**Comment by zegervdv** [comment]
Do you have `$XDG_CONFIG_HOME` set?
And if so, is it pointing to `$HOME/.config`?

**Comment by aravezskinteeth** [comment]
It seems that I don't have `$XDG_CONFIG_HOME` and maybe that's causing the issue. 

<img width="458" alt="SCR-20230313-dwu" src="https://user-images.githubusercontent.com/104392087/224742079-84eed311-f5f9-4401-9924-647ba9659169.png">

I'm not an expert in setting environmental variables, so I'm not sure if this is how you check if they're set.

**Comment by zegervdv** [comment]
You can do `export XDG_CONFIG_HOME=$HOME/.config`. 

Typically this is something you add to your shell config (e.g. .bashrc or .zshrc) but you can run it in the terminal so it is active for the current session. After doing that, does zathura pick up the configurations?

**Comment by aravezskinteeth** [comment]
It still doesn't work, and not event my mapped keybindings to zoom in and out and the selection to clipboard work. I already quit and reopened the terminal.

<img width="839" alt="SCR-20230313-eq8" src="https://user-images.githubusercontent.com/104392087/224751084-fcb94dac-a4c5-4590-813d-ab9b60685559.png">

And my `nvim` `init.lua` file isn't being read:

<img width="860" alt="SCR-20230313-em2" src="https://user-images.githubusercontent.com/104392087/224750497-92a1c4ff-817a-4575-8d77-7c6cdc4560d1.png">

Just in case this is what I have in my `~/.config/zathura`

<img width="541" alt="SCR-20230313-elx" src="https://user-images.githubusercontent.com/104392087/224751667-0710869c-422a-4087-b25c-b166831e5929.png">

**Comment by zegervdv** [comment]
Nice you figured it out. 
From your screenshot it seems the first trial it hadn't expanded the `$HOME` which caused nvim to also misbehave.
