### ISSUE TITLE
zathura-pdf-poppler's download link from macport seems broken

### ISSUE THREAD

**Issue by drselump14** [zegervdv/homebrew-zathura#11]
cannot install zathura-pdf-poppler because download link is invalid... 

` ➜  app  brew install zathura-pdf-poppler
` ==> Installing zathura-pdf-poppler from zegervdv/homebrew-zathura
` ==> Downloading https://pwmt.org/projects/zathura-pdf-poppler/download/zathura-p
` ######################################################################## 100.0%
` ==> Downloading https://trac.macports.org/browser/trunk/dports/office/zathura-pl
` curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received

**Comment by zegervdv** [comment]
The site seems to be down.
I'll try to find the cached diff files on my computer.
