### ISSUE TITLE
Pressing TAB causes Zathura to crash

### ISSUE THREAD

**Issue by Dorima1** [zegervdv/homebrew-zathura#110]
I get the following error
<img width="682" alt="image" src="https://user-images.githubusercontent.com/83615435/235618864-e6d7ae68-1b68-475b-b34e-91d836dd19f8.png">
I want to press TAB to see the table of contents to easily navigate. Any help with fixing this?

**Comment by zegervdv** [comment]
Is this on the latest release or head version? If release, can you try the head?

Either way, this might be an issue with zathura itself, so you may want to open a ticket there.

**Comment by Dorima1** [comment]
I used the head version and it works. Thank you!
