### ISSUE TITLE
Zathura does't open any documments.

### ISSUE THREAD

**Issue by aravezskinteeth** [zegervdv/homebrew-zathura#111]
I have no idea if this issue is from `zathura` itself or from `homebrew-zathura`. I followed all the installation instructions with the plugin included, and  it was working well. 

However, recently I'm getting this, which I don't know what it means:
```shell 
cannot create context: incompatible header (1.21.1) and library (1.22.0) 
versionserror: could not open document
```

**Comment by zegervdv** [comment]
Hm, a vague error. 

Did you install zathura with the syntex flag? 

Can you try installing zathura with the `--head` flag to see if that fixes it?

**Comment by aravezskinteeth** [comment]
Taking a look at my `Brewfile`, I installed zathura like this:

```rb
brew "zegervdv/zathura/girara", args: ["HEAD"]
brew "zegervdv/zathura/synctex"
brew "zegervdv/zathura/zathura", args: ["HEAD"]
brew "zegervdv/zathura/zathura-djvu"
brew "zegervdv/zathura/zathura-pdf-mupdf"
```

I don't know if this counts as installing zathura with the syntex flag.

**Comment by zegervdv** [comment]
I don't think so. I don't know how to add the option there but you could try to manually install it `brew reinstall zathura --head --synctex`.

**Comment by aravezskinteeth** [comment]
Finally fixed it. I realized I had two zathura version (without head and with head), so I uninstalled them all. 

Then I installed only the head version with the synctex flag. Also reinstalled and linked the pdf plugin.

**Comment by zegervdv** [comment]
Nice you found it!
The linking is annoying but I haven't found a way around it.
