### ISSUE TITLE
Zathura doesn't read zathurarc

### ISSUE THREAD

**Issue by abwats** [zegervdv/homebrew-zathura#117]
Hi, thank you so much for writing and maintaining this formula. I was able to install zathura on my Mac with the mupdf plugin and it seems to run fine. The only problem is zathura doesn't seem to read the zathurarc file I have put in ~/.config/zathura/zathurarc. When I run zathura -l debug, I can see that it is looking in the right place, and doesn't throw an error. But the lines of code I want to run at startup aren't run. If I just directly type them into the prompt in zathura they work fine. Any help with this would be very much appreciated. For example, if there is some other debug command I could run to try to diagnose why the zathurarc is being ignored. I apologize if I am posting in the wrong place, please let me know where I should ask this question instead. Thanks a lot.

**Comment by zegervdv** [comment]
Have you set `export XDG_CONFIG_HOME=$HOME/.config`?

Not sure if it is needed if you say it is reading from the right location, though. But can't hurt to try.

**Comment by abwats** [comment]
I don't fully understand what I did, but somehow I have fixed the problem. I upgraded mupdf-tools to the latest version, and unlinked mupdf. Now zathurarc is getting read. Thanks for your help!
