### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by worrybeads** [zegervdv/homebrew-zathura#12]
Hello it's possible to update the repository?
The actual version is 0.3.6 and your repository is on 0.3.4

Thank you

**Comment by zegervdv** [comment]
I'm currently having some issues to get the latest version compiled. But I'm looking into it.

**Comment by zegervdv** [comment]
Finally got around to fixing those compile issues. Sadly no fix for #10 yet, but I something about this compile issue still seems fishy. Will try to investigate it further.
