### ISSUE TITLE
Sequoia issues

### ISSUE THREAD

**Issue by mjachi** [zegervdv/homebrew-zathura#129]
Recent update to Sequoia has broken something.

![Screenshot 2024-09-19 at 3 15 01 AM](https://github.com/user-attachments/assets/887c4c27-7a8b-4ea3-b072-c6ad5d529f0d)

This issue is popping up elsewhere:
- https://www.reddit.com/r/emacs/comments/1fj0ooy/emacs_on_sequoia/
- https://github.com/dotnet/maui/issues/24794

I'm not sure if anything can actually be done here though?

**Comment by nowjiin** [comment]
I'm experiencing the same thing

Is this message pops up on terminal or IDE console?

**Comment by mjachi** [comment]
There should be no difference. The above is just from my terminal trying to open a random PDF I have (rather than anything with VimTex)

**Comment by nowjiin** [comment]
Why This Message Appears

	1.	Input Method Kit (IMK):
	•	macOS uses the Input Method Kit (IMK) to handle keyboard input and text input methods, including internationalization and other text input scenarios.
	•	When a Python application initializes certain GUI frameworks or interacts with the graphical user interface, macOS tries to determine which IMKClient and IMKInputSession subclasses to use for handling input.
	2.	IMKClient_Legacy and IMKInputSession_Legacy:
	•	The messages indicate that macOS is using legacy versions of IMKClient and IMKInputSession for handling input. This usually happens when the Python process does not fully support or register with the latest macOS input systems.
	3.	Python GUI Frameworks:
	•	GUI frameworks such as OpenCV, matplotlib, or Tkinter may trigger this log when they create windows or handle user input. This is because they might not be optimized for the latest macOS input system APIs.
	4.	Logging Behavior:
	•	macOS logs this information for diagnostic purposes, but it does not impact the functionality of your Python script. It’s essentially just informational output.

How to Suppress or Address the Issue

	1.	Ignore the Logs:
	•	Since these logs do not affect your program’s functionality, the simplest approach is to ignore them.
	2.	Suppressing Warnings in Python:
	•	If you find the logs annoying, you can suppress such output by setting environment variables or redirecting stderr. For example, you can run your Python script with:
	`python -W ignore script.py`
	•	This will suppress warnings, but may not completely remove these specific logs.

Quick Answer from GPT.
I did not tried python script but, hope this will help thx.

**Comment by zegervdv** [comment]
@mjachi  have you tried removing and reinstalling (i.e., recompiling)?

**Comment by mjachi** [comment]
Ah reading the error message makes it clear that I should have tried doing so.

Just did `brew reinstall zathura` and fixed the error, but it is still warning about `IMKClient` and `IMKInputSession` versioning.

**Comment by zegervdv** [comment]
I suspect that warning is coming from gtk. It will probably get resolved eventually

**Comment by torarnv** [comment]
The log comes from a non-categorized `NSLog` in `+[IMKClient subclass]` and `+[IMKInputSession subclass]`, and whether `IMKClient_Modern` or `IMKClient_Legacy` is in use doesn't change whether the `NSLog` is called.

It doesn’t seem to output when running via Xcode, presumably because Xcode filters it out in its oslog shim.

It does however pop up when running an app via the terminal.

**Comment by memark** [comment]
@mgroth0 I get a page with "Feedback Not Found" following your link.

>you can suppress such output by setting environment variables
@nowjiin What env var would that be?

**Comment by nowjiin** [comment]
@memark env var is meaning mac os version?

**Comment by memark** [comment]
> @memark sorry, env var is meaning mac os version?

@nowjiin "env var" = "environment variable"
