### ISSUE TITLE
Add support for djvu

### ISSUE THREAD

**Issue by mikeonly** [zegervdv/homebrew-zathura#16]
Hi, there is [djvu plugin](https://pwmt.org/projects/zathura-djvu/) available for Linux zathura. Is there a chance that it can be added to this formula?

The only issue I remember with this plugin is that it requires a [patch from macports](https://trac.macports.org/browser/trunk/dports/office/zathura-plugin-djvu/Portfile) to run on macOS. It would be great if this patch can be included here.

Thanks.

**Comment by zegervdv** [comment]
I haven't been able to test it though so if you see any problems you can reopen this.
