### ISSUE TITLE
synctex support

### ISSUE THREAD

**Issue by elanini** [zegervdv/homebrew-zathura#17]
I am unable to compile zathura with synctex support.

I have just installed MacTex2016 using the pkg from their site and linked with FixLink.pkg

This is the output of --help:
```$ zathura --help
Usage:
  zathura [OPTION…]  [file1] [file2] [...]

Help Options:
  -h, --help                  Show help options

Application Options:
  -e, --reparent=xid          Reparents to window specified by xid (X11)
  -c, --config-dir=path       Path to the config directory
  -d, --data-dir=path         Path to the data directory
  --cache-dir=path            Path to the cache directory
  -p, --plugins-dir=path      Path to the directories containing plugins
  --fork                      Fork into the background
  -w, --password=password     Document password
  -P, --page=number           Page number to go to
  -l, --log-level=level       Log level (debug, info, warning, error)
  -v, --version               Print version information
  --mode=mode                 Start in a non-default mode
```

Looking at the makefile, it checks for synctex with pkg-config synctex, which fails, disabling synctex. If it is enabled, <synctex/synctex_parser.h> is included, which doesn't exist on my system. 

Is there any way to compile with synctex support?

**Comment by zegervdv** [comment]
I added a `--with-synctex` option which should install synctex and link to it correctly.
Haven't tested it functionally though, so feel free to open a new issue if it doesn't work properly.
