### ISSUE TITLE
Zathura failling to install

### ISSUE THREAD

**Issue by KonVas** [zegervdv/homebrew-zathura#18]
Hi, I am getting this 
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "girara"
Download failed: https://pwmt.org/projects/girara/download/girara-0.2.7.tar.gz

**Comment by zegervdv** [comment]
Seems like something went wrong with their server. Hopefully it is not permanent.

**Comment by zegervdv** [comment]
They seem to be back online. Is the issue still occurring?

**Comment by KonVas** [comment]
Seems alright.
