### ISSUE TITLE
zathura windows on macOS

### ISSUE THREAD

**Issue by phlind** [zegervdv/homebrew-zathura#20]
When a zathura windows is opened, I can't control it with my shortcuts from BetterTouchTool and I can't close it with the standard macOS shortcuts CMD+w. So it seams like the window is not considered a "normal" window for macOS. Is there any possiblity to let it eather be treated as a normal window or at least let it spawn in a certain position on screen (defined by pixels)? 

Also it would be nice if I could remove the titlebar at the top of the window (where the name of the file is displayed) completely. But that's not really an issue.

**Comment by zegervdv** [comment]
The zathura window is drawn using Xquartz (X11 for macOS basically) and the windows do not behave exactly the same as normal windows. Sadly, BetterTouchTool has no support for X11, see fifafu/BetterTouchTool#575

As far as customizing the size and place of the window or the titlebar goes, I have no idea, but you may have some luck searching for Xquartz customization.
