### ISSUE TITLE
zathura-pdf-poppler failed to install (Calling <<-EOS.undent is disabled!)

### ISSUE THREAD

**Issue by lxndrcx** [zegervdv/homebrew-zathura#21]
==> Installing zegervdv/zathura/zathura-pdf-poppler
==> Downloading https://pwmt.org/projects/zathura-pdf-poppler/download/
######################################################################## 100.0%
==> make
==> make install
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/zegervdv/homebrew-zathura/zathura-pdf-poppler.rb:47:in `caveats'
Please report this to the zegervdv/zathura tap!
Or, even better, submit a PR to fix it!

**Comment by zegervdv** [comment]
Thanks for letting me know!
