### ISSUE TITLE
Failed to download resource "girara"

### ISSUE THREAD

**Issue by Kwask94** [zegervdv/homebrew-zathura#32]
is it just me or there is an error downloading this package.. is there another way to complete installation.
```
curl: (22) The requested URL returned error: 504
Error: Failed to download resource "girara"
Download failed: https://pwmt.org/projects/girara/download/girara-0.2.9.tar.xz
zsh: exit 1     brew install zathura

```
thanks

**Comment by zegervdv** [comment]
It seems like their website is down. Try again later?

**Comment by zegervdv** [comment]
Their website is back up apparently, but I've moved to the GitHub mirrors just to be safe.

**Comment by zegervdv** [comment]
No, the building of the bottle failed and left some residue of the last one. Should work again after a `brew update`.
