### ISSUE TITLE
Installation of Zathura via Brew stopped on dependency GTK+3

### ISSUE THREAD

**Issue by scottbaron** [zegervdv/homebrew-zathura#4]
➜  ~  brew install zathura
==> Installing zathura from zegervdv/homebrew-zathura
==> Installing dependencies for zegervdv/zathura/zathura: gtk+3, girara
==> Installing zegervdv/zathura/zathura dependency: gtk+3
==> Downloading https://download.gnome.org/sources/gtk+/3.16/gtk+-3.16.3.tar.xz
Already downloaded: /Library/Caches/Homebrew/gtk+3-3.16.3.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gtk+3/3.16.3 --disable-glibtest --ena
==> make install
gtksettings.c:910: Warning: Gtk: unexpected annotation: element-type
Command '['/private/tmp/gtk+320150604-28348-qf2q3w/gtk+-3.16.3/gtk/tmp-introspectSKIjS0/Gtk-3.0', '--introspect-dump=/private/tmp/gtk+320150604-28348-qf2q3w/gtk+-3.16.3/gtk/tmp-introspectSKIjS0/functions.txt,/private/tmp/gtk+320150604-28348-qf2q3w/gtk+-3.16.3/gtk/tmp-introspectSKIjS0/dump.xml']' returned non-zero exit status -11
make[2]: *** [Gtk-3.0.gir] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting

Any idea on how to get through this error. I can post brew doctor output if you want it.

**Comment by zegervdv** [comment]
From the output in #3, I saw this line:
```
export GDK_PIXBUF_MODULEDIR="/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders"
```
Not sure if it has something to do with it, but it wouldn't hurt to run this before trying to install.
If it still doesn't work, maybe you should raise an issue with Homebrew, they will probably know more about this.
