### ISSUE TITLE
New windows do not autofocus

### ISSUE THREAD

**Issue by jumban** [zegervdv/homebrew-zathura#41]
When opening any document with zathura, the window does not gain focus automatically, and I have to use CMD+Tab to switch to the zathura window manually each time.

I'm wondering, is this the normal behaviour on MacOS? 

Thank you.

**Comment by zegervdv** [comment]
That is a side effect of using xQuartz for rendering. See #38. 

I don’t think there’s anything to be done about it I’m afraid.

**Comment by jumban** [comment]
Thanks for the prompt response @zegervdv.

Was hoping that they were separate issues but thank you for clarifying.

I would also greatly appreciate if anyone have any workarounds to this as I often have many applications open and the zathura window spawns in seemingly random positions and having to use CMD + Tab to look for it is a little cumbersome.

**Comment by zegervdv** [comment]
Hey, just pushed new versions of girara and zathura, without XQuartz, so maybe it works now?

**Comment by jumban** [comment]
Will try it when I get a chance and report back, thanks!

**Comment by jumban** [comment]
I have updated zathura via homebrew upgrade zathura. When I run zathura --version:
> zathura 0.4.5
> girara 0.3.4 (runtime: 0.3.4)
> (plugin) pdf-poppler (0.3.0) (/usr/local/Cellar/zathura/0.4.5/lib/zathura/libpdf-poppler.dylib)

However, there does not appear to be any change in the behaviour of the window. The zathura window still doesn't focus automatically my window managers such as BetterTouchTool and chunkwm are still unable to detect it.

**Comment by zegervdv** [comment]
Some changes have been proposed in #38. Once they get merged and released this may also solve this problem.  Closing for now.
