### ISSUE TITLE
Synctex option not showing up

### ISSUE THREAD

**Issue by jumban** [zegervdv/homebrew-zathura#43]
Hi, I have been using zathura as my main PDF viewer and absolutely love it. I am now trying to set it up for synctex with VSCode. 

However, even after installing zathura with `brew install zathura --with-synctex`, the synctex still do not show up when I issue `zathura -h`. 

How do I get synctex to work with zathura?

Any help will be greatly appreciated, thank you!

**Comment by zegervdv** [comment]
I’ve never used it myself and only added it for a previous issue. It’s possible that an update broke it again. I’ll have to take a look at the build options. Can you try to install again with a verbose setting?

**Comment by jumban** [comment]
Hi, I just reinstalled it with the --verbose option. Hope that this helps. 

`==> Reinstalling zegervdv/zathura/zathura --with-synctex
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200207-12459-o7u0li.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/zegervdv/homebrew-zathura/zathura.rb --verbose --with-synctex
==> Downloading https://github.com/pwmt/zathura/archive/0.4.4.tar.gz
Already downloaded: /Users/Jiahui/Library/Caches/Homebrew/downloads/d034fb89f7ee33fcb9548afdb0fc5a3ba1c720d7e3f94407e6d6255b03b3ac20--zathura-0.4.4.tar.gz
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura/0.4.4
==> cd build && ninja && ninja install
==> Cleaning
==> Finishing up
ln -s ../Cellar/zathura/0.4.4/bin/zathura zathura
ln -s ../Cellar/zathura/0.4.4/include/zathura zathura
ln -s ../../Cellar/zathura/0.4.4/share/applications/org.pwmt.zathura.desktop org.pwmt.zathura.desktop
ln -s ../../../Cellar/zathura/0.4.4/share/bash-completion/completions/zathura zathura
ln -s ../Cellar/zathura/0.4.4/share/dbus-1 dbus-1
mkdir -p /usr/local/share/fish/completions
ln -s ../../../Cellar/zathura/0.4.4/share/fish/completions/zathura.fish zathura.fish
ln -s ../../../../../Cellar/zathura/0.4.4/share/icons/hicolor/128x128/apps/org.pwmt.zathura.png org.pwmt.zathura.png
ln -s ../../../../../Cellar/zathura/0.4.4/share/icons/hicolor/16x16/apps/org.pwmt.zathura.png org.pwmt.zathura.png
ln -s ../../../../../Cellar/zathura/0.4.4/share/icons/hicolor/256x256/apps/org.pwmt.zathura.png org.pwmt.zathura.png
ln -s ../../../../../Cellar/zathura/0.4.4/share/icons/hicolor/32x32/apps/org.pwmt.zathura.png org.pwmt.zathura.png
mkdir -p /usr/local/share/icons/hicolor/64x64
mkdir -p /usr/local/share/icons/hicolor/64x64/apps
ln -s ../../../../../Cellar/zathura/0.4.4/share/icons/hicolor/64x64/apps/org.pwmt.zathura.png org.pwmt.zathura.png
mkdir -p /usr/local/share/icons/scalable
mkdir -p /usr/local/share/icons/scalable/apps
ln -s ../../../../Cellar/zathura/0.4.4/share/icons/scalable/apps/org.pwmt.zathura.svg org.pwmt.zathura.svg
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/ar/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/ca/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/cs/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/de/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/el/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/eo/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/es/LC_MESSAGES/zathura.mo zathura.mo
mkdir -p /usr/local/share/locale/es_CL
mkdir -p /usr/local/share/locale/es_CL/LC_MESSAGES
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/es_CL/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/et/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/fr/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/he/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/hr/LC_MESSAGES/zathura.mo zathura.mo
mkdir -p /usr/local/share/locale/id_ID
mkdir -p /usr/local/share/locale/id_ID/LC_MESSAGES
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/id_ID/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/it/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/lt/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/nl/LC_MESSAGES/zathura.mo zathura.mo
mkdir -p /usr/local/share/locale/no
mkdir -p /usr/local/share/locale/no/LC_MESSAGES
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/no/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/pl/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/pt_BR/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/ru/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/sv/LC_MESSAGES/zathura.mo zathura.mo
mkdir -p /usr/local/share/locale/ta_IN
mkdir -p /usr/local/share/locale/ta_IN/LC_MESSAGES
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/ta_IN/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/tr/LC_MESSAGES/zathura.mo zathura.mo
mkdir -p /usr/local/share/locale/uk_UA
mkdir -p /usr/local/share/locale/uk_UA/LC_MESSAGES
ln -s ../../../../Cellar/zathura/0.4.4/share/locale/uk_UA/LC_MESSAGES/zathura.mo zathura.mo
ln -s ../../../Cellar/zathura/0.4.4/share/man/man1/zathura.1 zathura.1
ln -s ../../../Cellar/zathura/0.4.4/share/man/man5/zathurarc.5 zathurarc.5
ln -s ../../Cellar/zathura/0.4.4/share/metainfo/org.pwmt.zathura.appdata.xml org.pwmt.zathura.appdata.xml
ln -s ../../../Cellar/zathura/0.4.4/share/zsh/site-functions/_zathura _zathura
ln -s ../../Cellar/zathura/0.4.4/lib/pkgconfig/zathura.pc zathura.pc
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200207-12796-pa4u51.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/zegervdv/homebrew-zathura/zathura.rb
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/zathura/0.4.4: 52 files, 701.9KB, built in 25 seconds`

**Comment by Zeta611** [comment]
I can reproduce this issue. I recently clean installed my mac, and `brew install zathura --with-synctex` does not seem to work anymore. It did work the last time I installed zathura about two months ago..

**Comment by zegervdv** [comment]
Seems like the last zathura update upstepped the synctex version. Will need to find the newer one to build.

**Comment by zegervdv** [comment]
just pushed synctex 1.21, so it should build again. Make sure to update synctex first.

**Comment by zegervdv** [comment]
Pushed an extra update, make sure it installs `1.21.0_1` to get all the fixes.
I have not used synctex myself, so please test functionally to make sure everything works.
