### ISSUE TITLE
font size in zathura

### ISSUE THREAD

**Issue by MarkusLohmayer** [zegervdv/homebrew-zathura#45]
Dear zathura developers and users,
I have two problems with using zathura regarding the size of its user interface elements.
The command line text (say when I type `:set recolor` is much to small for my eyes.
Secondly, the font size of the outline (when I hit the Tab key) is also too small for my eyes.
I have spent lot's of time trying to find information regarding this related to zathura and also XQuartz but I din't find anything useful.
Best,
Markus

**Comment by zegervdv** [comment]
Just to be clear, I am not the developer of Zathura. I only provide the packaging for homebrew.
If you want to get in touch with them check https://pwmt.org.

Do you have a hi-DPI display like a retina macbook pro?
Getting rid of the XQuartz dependency would probably solve a lot of these issues but that would probably require more thorough changes in the Zathura and Girara (the GTK wrapper library).

**Comment by MarkusLohmayer** [comment]
@zegervdv Thanks for your answer.
I am having a retina display. I thought other mac users might have figured out how to increase the font size. But maybe there is no straightforward way to do it!

**Comment by zegervdv** [comment]
There was #9 which was fixed (partially) when updating to 0.3.9, but I see from the attached screenshot the command line is still quite small. I'll try to find some time to do some more digging in the source code, maybe some hacks can be implemented.

**Comment by MarkusLohmayer** [comment]
@zegervdv Thanks so much for your work in making zathura available on macOS!

**Comment by zegervdv** [comment]
I discovered I don't actually need the XQuartz library anymore.
Sadly that does not seem to improve the size of the statusbar.

However, GTK allows to override just about every style element using css.
So after digging through the code I found a way to increase the font-size of the bar.

Create a folder `~/.config/gtk-3.0` with a file named `gtk.css`.
Add this (adjust for desired font-size):
``` css
.bottom_box {
    font-size: 12px;
}
```

**Comment by MarkusLohmayer** [comment]
Interesting! Will getting rid of this dependency (XQuartz) still make it possible to have zathura run over `ssh -X ...` (ssh routing of X11 window system)?

And WOW, @zegervdv you are my morning hero! Incredible how fast you offered the solution!
Thanks :)

Is it possible to also do the same for the font that is used for the document outline,
i.e. what you get if you press `tab`?

**Comment by zegervdv** [comment]
I assume that should still work, but haven't tested it.
If it works for other mac applications it should.

I'll need to make full list of elements to apply the style overrides to.

**Comment by zegervdv** [comment]
Some of the other elements:

```
completion-box
completion-group
completion
```

I'm still trying to find the class for the shortcut labels (like when you press `f`).

You could of course try the 'nuclear' option and do this:
``` css
* {
    font-size: 12px;
}
```
But that may have unintended side-effects.

**Comment by basbebe** [comment]
this also works:

```
set font 'monospace normal 14'
```

can be seth in zathura or in `~/.config/zathura/zathurarc`

**Comment by sdyalor** [comment]
Close this, Anwer from @basbebe fix it :)
