### ISSUE TITLE
Zathura opening pdf: Unknown file type

### ISSUE THREAD

**Issue by APeyko** [zegervdv/homebrew-zathura#46]
When i try to use Zathura to open any .pdf file i get an error, i followed install guide with the following:
$brew install Zathura
$brew install zathura-pdf-poppler
$ mkdir -p $(brew --prefix zathura)/lib/zathura
$ ln -s $(brew --prefix zathura-pdf-poppler)/libpdf-poppler.dylib $(brew --prefix zathura)/lib/zathura/libpdf-poppler.dylib

Now when i try to open a pdf, i get an error message in terminal, and zathura opens with a black screen.
Command i used to open pdf:
$zathura Uge50.pdf 
i also tried a pdf i made in vimtex, with the same result.
Error message:
`error:` Unknown file type: 'dyn.agq80g2psr311kkdtsbw06kdaf741g3pwsq10c5dftbu063dfsm2gn8pytk11n35fgy2c66deq2xwandsr6uhg7pdraugq4pqqyug86vaqvy1e3pdsv11e8mm'

Upon seeing [this issue](https://github.com/zegervdv/homebrew-zathura/issues/44)
I have now done
$brew install zathura-pdf-mupdf
and afterwards:
$ln -s $(brew --prefix zathura-pdf-mupdf)/libpdf-mupdf.dylib $(brew --prefix zathura)/lib/zathura/libpdf-mupdf.dylib

Which still doesent resolve the issue.

**Comment by zegervdv** [comment]
Did you try reinstalling girara/zathura?
Can you also try with the latest updates, pushed a few minutes ago?

**Comment by APeyko** [comment]
I have now uninstalled zathura, zathura-pdf-poppler and zathura-pdf-mupdf. using homebrew
Did the following:
$brew upgrade girara
$brew tap zegervdv/zathura
$brew install zathura
$brew install zathura-pdf-poppler
And what told in terminal prompt and in your readme
$ mkdir -p $(brew --prefix zathura)/lib/zathura
$ ln -s $(brew --prefix zathura-pdf-poppler)/libpdf-poppler.dylib $(brew --prefix zathura)/lib/zathura/libpdf-poppler.dylib
Afterwards i still only get a black screen when opening any pdf.
When doing
$brew upgrade zathura
or
$brew upgrade zathura-pdf-poppler
it tells me that i already have zathura version 0.4.5 and zathura-pdf-poppler 0.3.0 installed

**Comment by zegervdv** [comment]
so you have the same error for mupdf and poppler?

**Comment by APeyko** [comment]
I dont know how to switch between mupdf and poppler. Maybe i havent been using the plugins?
i am trying to open a pdf "test.pdf" in terminal doing the following:
$zathura test.pf

**Comment by APeyko** [comment]
You can close the issue, i now see that you have to declare the path to the file running
$zathura /Users/myusername/Desktop/test.pdf
i has opened
