### ISSUE TITLE
Zathura not opening PDFs, throwing error on -v

### ISSUE THREAD

**Issue by marekkowalczyk** [zegervdv/homebrew-zathura#48]
`$ zathura test.pdf`

`error: could not open plugin directory: /usr/local/Cellar/zathura/0.4.5/lib/zathura`

`error: Could not determine file type.` 

— and hangs.

`$ zathura -v`

`error: could not open plugin directory: /usr/local/Cellar/zathura/0.4.5/lib/zathura`

`zathura 0.4.5`

`girara 0.3.4 (runtime: 0.3.4)`

Reinstalling etc. doesn't help.

**Comment by zegervdv** [comment]
Seems like you didn’t run the commands after installing the pdf plugin.

**Comment by marekkowalczyk** [comment]
I’m sorry I don’t quite get it. Can you please specify the proper sequence? 

I believe I did everything as per earlier discussions here.

**Comment by zegervdv** [comment]
Well it is literally saying it cannot find the plugins dir. Did you install a pdf plugin like zathura-pdf-poppler and follow the instructions to symlink the plugin in place?

**Comment by marekkowalczyk** [comment]
I have re-installed everything and it works.
