### ISSUE TITLE
Copy text not working

### ISSUE THREAD

**Issue by geigi** [zegervdv/homebrew-zathura#5]
First: Thanks for this formula! 

Now to the issue: when dragging with the mouse over text zathura copies the text to the clipboard. This seems not to work because when pasting the text somewhere else the text is not in the clipboard.

Running 10.10.4

**Comment by geigi** [comment]
I discovered that zathura is using the x11 primary selection as default instead of the actual clipboard. This can be changed by creating a `~/.config/zathura/zathurarc` file with the following content:
```
set selection-clipboard clipboard
```

**Comment by zegervdv** [comment]
Thanks! 
I've added this to the README.

**Comment by jashawnyu** [comment]
well done!
