### ISSUE TITLE
Making Zathura the Default PDF Viewer

### ISSUE THREAD

**Issue by jshaker000** [zegervdv/homebrew-zathura#51]
Do you know if this is possible given that it doesnt have a .app style package?

**Comment by zegervdv** [comment]
I think this is related to #49. 
Currently zathura is basically compiled as a Unix program. I am not sure if it is possible to create a .app without making larger modifications to the source code (which is out of my scope).

**Comment by m-zheng** [comment]
It's possible with Apple Automator. You can follow instructions [here](https://gist.github.com/agzam/76d761804330cc8c4600fccda952ed1c).
