### ISSUE TITLE
Is it opened in the terminal?

### ISSUE THREAD

**Issue by weikang-q** [zegervdv/homebrew-zathura#54]
I've seen many videos in which they use zathura on Linux. It seems that zathura is opened in the terminal (maybe I am wrong because I am not familiar with it). But I am using MacOS, when I open zathura, it just open a new window and displays the pdf in that window. Is it its behavior?

**Comment by zegervdv** [comment]
It is opened via the terminal, but it opens in a separate window to be able to show the graphics. Some terminals can show images, but I have not seen zathura inside a terminal. 

Opening from the terminal is the way to use it both on Linux and macOS.

**Comment by weikang-q** [comment]
The icon is like this
<img width="72" alt="Screen Shot 2020-05-19 at 7 42 57 PM" src="https://user-images.githubusercontent.com/56542320/82322345-f17ae380-9a08-11ea-93fd-5b896c133eb3.png">
and the window is like this
<img width="912" alt="Screen Shot 2020-05-19 at 7 44 43 PM" src="https://user-images.githubusercontent.com/56542320/82322496-3141cb00-9a09-11ea-9832-7a6ad537e654.png">
and I do not think that's a terminal.

by the way, there's an error
`Failed creating new xdo instance`
(I am not sure is it related to this issue.)

**Comment by zegervdv** [comment]
No that is not a terminal. It is opened from a terminal. The zathura application itself is no terminal, not on macOS or on Linux. 

Those messages can be safely ignored.

**Comment by weikang-q** [comment]
Got it! Thanks so much.
