### ISSUE TITLE
Make it behave like a Cocoa App

### ISSUE THREAD

**Issue by agzam** [zegervdv/homebrew-zathura#55]
Is it possible to make Zathura to act and behave like a Cocoa App?

- I want to be able to set Zathura as a default pdf viewer _I'm not sure if that's possible for cmd apps at all_;
- I want it to appear in Alfred/Spotlight. _And if the instance of it already running, searching in Alfred should switch to that instance, instead of spawning a new one;_
- Would be cool if it was possible to be able to set it to [OSX native] fullscreen;
- Would be awesome if there's a recognizable icon in the dock and the app-switcher;

**Comment by zegervdv** [comment]
For that to work some major changes are needed to the source code, probably outside the scope of what can be achieved with some patches. 

So unless the maintainers add native macOS support I don’t see this happening any time soon.

**Comment by agzam** [comment]
I tried using https://sveinbjorn.org/platypus to wrap it into a Cocoa App and it almost worked. I'm not a OSX/iOS developer, so I don't know the specifics, but that attempt made me believe that some of that perhaps could be done (?)

But of course you probably know better.

Please don't get me wrong, I'm not arguing, only trying to make a point - I use Zathura on Linux all the time, I want to use it on Mac as well, but not having a native Cocoa shell makes it (I wouldn't say useless) but a bit limited.

**Comment by agzam** [comment]
It seems this work is underway and maybe soon all that will be possible https://git.pwmt.org/pwmt/zathura/-/issues/150

**Comment by zegervdv** [comment]
I had not heard of platypus before, it may be possibility.
I think the gtk-osx integrations looks more promising.

**Comment by zegervdv** [comment]
Tracking the progress of the integration in #38
