### ISSUE TITLE
Missing a package while meson build

### ISSUE THREAD

**Issue by Prithiviksit** [zegervdv/homebrew-zathura#57]
The error message says

> ==> meson build --prefix /usr/local/Cellar/girara/0.3.4
>Last 15 lines from /Users/pingfang/Library/Logs/Homebrew/girara/02.0.3.4:
>2020-07-22 11:47:28 -0400

>meson build --prefix /usr/local/Cellar/girara/0.3.4

>Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.55.0/libexec/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'

>If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/zegervdv/homebrew-zathura/issues

Some caveats which I am not sure if they are relevant.
>==> Caveats
icu4c is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

>If you need to have icu4c first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc

>For compilers to find icu4c you may need to set:
  export LDFLAGS="-L/usr/local/opt/icu4c/lib"
  export CPPFLAGS="-I/usr/local/opt/icu4c/include"

>For pkg-config to find icu4c you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"

Some other caveats
>==> Caveats
>Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

>zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

**Comment by zegervdv** [comment]
This seems like an error in meson. You could try again some time later or remove the HEAD version requirement.
