### ISSUE TITLE
Unable to open epub

### ISSUE THREAD

**Issue by Debusan13** [zegervdv/homebrew-zathura#61]
Whenever I try to open an epub file I get met with this
```
~/ > zathura Documents/Textbooks/Nancy\ A.\ Hewitt_\ Steven\ F\ Lawson\ -\ Exploring\ American\ Histories,\ Volume\ 1_\ A\ Survey\ with\ Sources\ 1\(2019,\ Bedford\ Books\)\ -\ libgen.lc.epub
error: plugin: filetype already registered: com.adobe.pdf
error: Could not register plugin '/usr/local/Cellar/zathura/0.4.6/lib/zathura/libpdf-poppler.dylib'.
error: EPUB is locked by DRM
error: could not open document
```

Zathura does open but it is completely black.

I installed poppler and mupudf from the tap as well.

**Comment by zegervdv** [comment]
You should only install one of those plugins. Also, I'm not sure zathura can handle DRM protected documents.

**Comment by Debusan13** [comment]
I see, I figured out how to remove [drm protection](https://www.techradar.com/news/software/how-to-remove-ebook-drm-with-calibre-1291960) with a piece of Free and Open Source Software and it works like a charm. 

I'll close the thread
