### ISSUE TITLE
zathura-cb

### ISSUE THREAD

**Issue by AnikaSU** [zegervdv/homebrew-zathura#64]
According to zathura homepage, 
> The [zathura-cb plugin ](https://pwmt.org/projects/zathura-cb/) adds comic book support to zathura.

the plugin seemed not available in this repo

**Comment by zegervdv** [comment]
I'll see what I can do.

**Comment by zegervdv** [comment]
I'm currently unable to test it myself, but I've pushed the configuration for zathura-cb. 

Let me know if you have any issues and please include the logs if so.

**Comment by AnikaSU** [comment]
Great thanks for the effort!

On  `macOS 10.15.7 (19H15) | Darwin 19.6.0 (199506) ` running  `brew install zathura-cb` turned out `meson.build:53:0: ERROR: Unknown variable "prefix".`

Sry that I was not able to get the full log. For the log was stored in a temp directory `/private/tmp/zathura-cb-20201129-9890-19o6zkk/zathura-cb-0.1.8/build/meson-logs/meson-log.txt` and it vanished immediately after the brew install process.

Pls let me know if there's anything I could do.

**Comment by zegervdv** [comment]
I made a typo. Can you try again?

**Comment by AnikaSU** [comment]
- Thanks! I upgraded to `zathura 0.4.7` and tested with several documents, the results as follows:

  

- zathura version

  zathura 0.4.7
  girara 0.3.5 (runtime: 0.3.5)

  (plugin) pdf-mupdf (0.3.5) 
  (plugin) ps (0.2.6) 
  (plugin) cb (0.1.8) 
  (plugin) djvu (0.2.8) 

  ----

- `.pdf` and `.djvu`

  As far as I've tested, both formats of documents go along well with zathura.

- `.cbr`

  zathura errors sporadically  with  `.cbr`  files. That said, I can properly open several `.cbr` files but not [this one](http://libgen.rs/book/index.php?md5=A8E394B242CF810F629C20859096631F) , which throws a message  ` "Document does not contain any pages"`  in zathura, but could be opened properly via [YACReader](https://www.yacreader.com/) .

- `.epub`

  I can properly open several `.epub` files properly, but not [this one](http://libgen.rs/book/index.php?md5=1B50426312C7E0598835785A0EE0D5ED) , which throws following messages:

```bash
error: cannot find named zip archive entry
warning: svg: ignoring external image 'Image00000.jpg'
warning: table-row not inside table element
warning: table-cell not inside table-row element
```

​	Neither could I open [this one](http://libgen.rs/book/index.php?md5=1677CFEFE688E50BFCAEE79DD8416F26) , which throws following messages:

```bash
error: cannot find named zip archive entry
warning: svg: ignoring external image '../data/content-0001.jpg'
```

**Comment by zegervdv** [comment]
I guess that is probably more an issue of zathura or the plugin itself. I will try on a linux machine to see if I get similar errors.

**Comment by zegervdv** [comment]
Got the same errors, so seems more like a zathura/plugin issue. I suggest you report it over at https://git.pwmt.org/pwmt

**Comment by AnikaSU** [comment]
> Got the same errors, so seems more like a zathura/plugin issue. I suggest you report it over at https://git.pwmt.org/pwmt

Okay, got it. I'm closing this issue then.
