### ISSUE TITLE
error: Rendering failed (page X)

### ISSUE THREAD

**Issue by AnikaSU** [zegervdv/homebrew-zathura#65]
homebrew installed  `zathura 0.4.6`  reports error  `error: Rendering failed (page X)` when opening pdf documents. 

This issue is (I guess) the same as [described in the pmwt zathura repo](https://git.pwmt.org/pwmt/zathura/-/issues/159) . The pmwt developers claimed the issue was fixed by upgrading to `0.4.7` 

Is it possible to have an `homebrew-zathura` upgrade, too?

Thanks!

**Comment by zegervdv** [comment]
upgraded the plugin, let me know if you still see issues

**Comment by AnikaSU** [comment]
Thanks! comfirmed that `error: Rendering failed (page X)` is fixed after upgrading.

However, there are several documents won't open properly with zathura, which I documented under [here](https://github.com/zegervdv/homebrew-zathura/issues/64).

I'm closing this issue since the problem was fixd :)
