### ISSUE TITLE
Zathura fails recognition with Dock os x

### ISSUE THREAD

**Issue by TunnelThruTime** [zegervdv/homebrew-zathura#67]
Hello, 
running 10.14.6 Mojave 
Zathura 0.4.7

Currently Zathura is not recognized by mac Dock or App Switcher.
Clicking window also leads to no avail, so no hotkeys work,
although Zathura recognizes mouse input.

Love to get this sorted out

**Comment by zegervdv** [comment]
This is not something that can easily be fixed. Zathura uses X11/gtk as graphics, which are not really compatible with MacOS/Aqua. See #38 for some work in progress to improve the situation.
