### ISSUE TITLE
Annoying X11 dependence warning

### ISSUE THREAD

**Issue by terrychou** [zegervdv/homebrew-zathura#68]
Hi,

First of all, thanks for making this project so that I am able to use `zathura` on macOS too!

My problem is that I keep receiving the following warning after I have installed zathura-djvu:

`Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the zegervdv/zathura tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/zegervdv/homebrew-zathura/zathura-djvu.rb:12`

I have tried uninstalling and reinstalling, but this persists.

**Comment by zegervdv** [comment]
yes, it seems that warning is new.
Anyway, I don't think the dependency to x11 is needed anymore, so I've removed it.
I also updated the version to 0.2.9.

Let me know if this fixes your issue.

**Comment by terrychou** [comment]
Thanks for this fix and update. The warning I mentioned above indeed disappears.

However, another warning shows when I run `brew search zathura`:

`Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the zegervdv/zathura tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/zegervdv/homebrew-zathura/zathura-mupdf.rb:9`

Just for reference, I don't have `zathura-mupdf` but `zathura-pdf-mupdf` installed.

**Comment by zegervdv** [comment]
The zathura-mupdf was a temporary fix, when the mupdf version provided by homebrew was too new compared to the one the zathura plugin needed. I will remove it.

**Comment by terrychou** [comment]
After the latest update, the `zathura-mupdf` warning now is not showing anymore, thanks!
