### ISSUE TITLE
Zathura Warning Message

### ISSUE THREAD

**Issue by DuncanKeith** [zegervdv/homebrew-zathura#7]
When I open a pdf with Zathura I get the following error message:

`Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.`

I am running OS X 10.10.5

**Comment by zegervdv** [comment]
I have this as a warning, but Zathura works without a problem.
This is something for the developers of Zathura to fix, I only provided this formula for Homebrew for easier installation.
If it works, this is nothing to worry about, otherwise you'd better contact the [developers](pwmt.org).
