### ISSUE TITLE
Error: count not register plugin...

### ISSUE THREAD

**Issue by reportaman** [zegervdv/homebrew-zathura#71]
Hi, I installed both zathura-poppler followed by Zathura-mupdf plugins. Before I installed mupdf plugin, .epub file would not open, but I did not get any error messages either. Now I get this error message whenever I open a pdf or epub file:

```
error: plugin: filetype already registered: com.adobe.pdf
error: Could not register plugin '/opt/homebrew/Cellar/zathura/0.4.7/lib/zathura/libpdf-poppler.dylib'.
```

The files open fine, though ideally I would want to fix these error messages.

**Comment by reportaman** [comment]
Got it! Removed the symlink ``rm /opt/homebrew/opt/zathura/lib/zathura/libpdf-poppler.dylib``, and I don't get that error. Though mupdf prints error on a pdf poppler did not: it was something like ``invalid pdf object``, though pdf does seem to render correctly. Also, it happened only for 1 pdf so far... Is there a way to silence these error messages?

**Comment by zegervdv** [comment]
I don't know how to silence the errors, I have seem them before but they don't always seem to mean anything.
If it really bothers you, you better get in touch with the developers over at https://pwmt.org
