### ISSUE TITLE
Unable to send keys

### ISSUE THREAD

**Issue by TunnelThruTime** [zegervdv/homebrew-zathura#72]
When opening zathura application doesn't focus, can't register keys,
and doesn't appear in dock or window manager.
Just reinstalled to head version and that same issue persists. 
Any help would be great!

OSX 10.14 
Zathura 0.4.7 --HEAd
Girara 0.3.5 --HEAD

**Comment by zegervdv** [comment]
Have you tried the non-HEAD version?

**Comment by TunnelThruTime** [comment]
Thank you for getting back to me, however after doing a simple update with
`xcode-select --install
brew upgrade
`
Lack of due diligence on my part. Closing this issue.
