### ISSUE TITLE
Can't find the configuration file

### ISSUE THREAD

**Issue by ilidan16** [zegervdv/homebrew-zathura#88]
I successfully installed zathura on MacOS 12.2 using the following commands:
 ```
 $ git clone https://git.pwmt.org/pwmt/zathura.git
 $ cd zathura
 $ git checkout --track -b develop origin/develop
 $ mkdir build
 $ meson build
 $ cd build
 $ ninja
 $ ninja install
```
But i can't find the file `~/.config/zathura/zathurarc` at all. Could you suggest me where this locates on Mac?

Thanks.

**Comment by zegervdv** [comment]
You'll have to create it yourself.

**Comment by ilidan16** [comment]
I tried to do it, but it doesn't work. I also was using the command `:source` inside zathura it does't give an answer.

**Comment by zegervdv** [comment]
You may need to `export XDG_CONFIG_HOME=$HOME/.config`.

**Comment by ilidan16** [comment]
It helped. Thank you for the advice!
